// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKBgy-SjNfaAUyOSD--I3mqSRqjhGHGAg',
    appId: '1:436812253151:web:89c5d310176ea284f8a66a',
    messagingSenderId: '436812253151',
    projectId: 'typroject-e3112',
    authDomain: 'typroject-e3112.firebaseapp.com',
    storageBucket: 'typroject-e3112.appspot.com',
    measurementId: 'G-71218DMVS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkH-hgeknXmku49V_WP0J04zZ2iJOMqdw',
    appId: '1:436812253151:android:236fddffc6cc9aa0f8a66a',
    messagingSenderId: '436812253151',
    projectId: 'typroject-e3112',
    storageBucket: 'typroject-e3112.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-g0jT0tUTLhDv2z7MJjN-n1jLd0Lrwn4',
    appId: '1:436812253151:ios:8a0f77e9b971dc53f8a66a',
    messagingSenderId: '436812253151',
    projectId: 'typroject-e3112',
    storageBucket: 'typroject-e3112.appspot.com',
    androidClientId: '436812253151-7ojrqkvpkro2pppukc6f0hsbsp7o1pmn.apps.googleusercontent.com',
    iosClientId: '436812253151-slqvjirgpput0402f7sstr1cvb8nsqk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.typroject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-g0jT0tUTLhDv2z7MJjN-n1jLd0Lrwn4',
    appId: '1:436812253151:ios:8a0f77e9b971dc53f8a66a',
    messagingSenderId: '436812253151',
    projectId: 'typroject-e3112',
    storageBucket: 'typroject-e3112.appspot.com',
    androidClientId: '436812253151-7ojrqkvpkro2pppukc6f0hsbsp7o1pmn.apps.googleusercontent.com',
    iosClientId: '436812253151-slqvjirgpput0402f7sstr1cvb8nsqk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.typroject',
  );
}
